# Change back to node_js when OSX agents have nvm pre-installed
language: ruby
os:
  - linux
  - osx
rvm: '1.9.3'
sudo: false
env:
  matrix:
    - NODE_VERSION="0.10"
    - NODE_VERSION="0.12"
    - NODE_VERSION="4"
notifications:
  email:
    - jhaynie@appcelerator.com
script:
  - ./travis.sh
